POST localhost:7070/api/ticket/populate

###

// TICKET ROUTES

GET localhost:7070/api/ticket/all
###

GET localhost:7070/api/ticket/5

###
POST localhost:7070/api/ticket/create
Content-Type: "application/json"

{
  "id": 7,
  "purchaseDate": "2025-04-01",
  "price": 99.99,
  "seatNumber": 12
}

###
PUT localhost:7070/api/ticket/1
Content-Type: "application/json"

{
  "id": 2,
  "purchaseDate": "2028-04-01",
  "price": 1,
  "seatNumber": 1337
}

###
DELETE localhost:7070/api/ticket/1

// EVENT ROUTES

###
GET localhost:7070/api/event/search/conference